const TEXT = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eget faucibus dui. Proin egestas mi nec hendrerit elementum. Cras hendrerit eros et quam dapibus condimentum. Suspendisse hendrerit ligula a tellus dictum pellentesque. Nullam tempor quis libero vel venenatis. Pellentesque nec feugiat velit. Ut sollicitudin justo sit amet justo maximus, ut posuere felis ullamcorper. Vestibulum venenatis velit id turpis luctus tristique in eu erat. Nullam vel blandit orci.\n" +
    "\n" +
    "Donec quis tincidunt dui, a pretium nulla. Cras viverra scelerisque arcu, sed gravida libero maximus ac. Nunc accumsan quam magna, quis aliquet arcu luctus id. Donec fermentum maximus ipsum quis laoreet. Etiam sit amet tortor velit. Proin consequat placerat pulvinar. Suspendisse suscipit, turpis ac sollicitudin pellentesque, sem eros rutrum magna, ut fringilla elit dolor a diam. Phasellus vestibulum urna in tortor ornare, id convallis metus sodales. Mauris aliquam volutpat justo in egestas. Integer aliquet nunc sed felis feugiat, et laoreet ligula malesuada. Praesent eu gravida est. Vivamus fermentum volutpat luctus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam finibus eros lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n" +
    "\n" +
    "Phasellus maximus erat at eros iaculis, nec feugiat lacus aliquet. Nam nibh ante, tincidunt et sem nec, finibus aliquam risus. Nunc non risus vitae sapien feugiat elementum sed vel orci. Mauris dui ante, viverra a tincidunt vel, egestas id mi. Vestibulum non arcu eget lorem suscipit sagittis in non turpis. Nullam molestie nibh posuere augue elementum vulputate. Nulla non ex id tellus molestie blandit ac id odio. Pellentesque ac ex ullamcorper, hendrerit diam ut, laoreet nunc.\n" +
    "\n" +
    "Nulla at orci augue. Pellentesque volutpat dolor ut felis convallis, sit amet imperdiet velit ornare. Pellentesque quis nunc venenatis, bibendum mi nec, pretium dui. Sed consequat orci vitae volutpat hendrerit. Nam bibendum massa metus, cursus bibendum nulla consequat non. Vestibulum in auctor elit. Donec risus ipsum, tempor et dui ac, vulputate ornare nibh. Integer convallis nisi non est finibus luctus.\n" +
    "\n" +
    "Ut porttitor imperdiet hendrerit. In semper dui eu diam ultrices tempus. Aliquam et magna vestibulum tortor lacinia accumsan sed ac lacus. Quisque hendrerit enim nibh, quis pellentesque diam volutpat id. Nullam sit amet hendrerit tellus. Pellentesque vestibulum pellentesque erat, ac elementum lectus vehicula vel. Nulla feugiat varius augue eget varius.";

export default TEXT;